"""create table

Revision ID: 9883888730f2
Revises: 
Create Date: 2026-02-11 14:57:13.882041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9883888730f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_index(op.f('ix_User_login'), 'User', ['login'], unique=False)
    op.create_index(op.f('ix_User_password'), 'User', ['password'], unique=False)
    op.create_table('Аuthor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Аuthor_id'), 'Аuthor', ['id'], unique=False)
    op.create_index(op.f('ix_Аuthor_name'), 'Аuthor', ['name'], unique=False)
    op.create_table('Post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['Аuthor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Post_id'), 'Post', ['id'], unique=False)
    op.create_index(op.f('ix_Post_title'), 'Post', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Post_title'), table_name='Post')
    op.drop_index(op.f('ix_Post_id'), table_name='Post')
    op.drop_table('Post')
    op.drop_index(op.f('ix_Аuthor_name'), table_name='Аuthor')
    op.drop_index(op.f('ix_Аuthor_id'), table_name='Аuthor')
    op.drop_table('Аuthor')
    op.drop_index(op.f('ix_User_password'), table_name='User')
    op.drop_index(op.f('ix_User_login'), table_name='User')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
